image: everledgerio/golang:1.15.0-alpine3.12

pipelines:
  default: # run pipeline for all branches
    - parallel:
        - step:
            name: Run chaincode unit tests
            script:
              # do this to make go module work with private repo (e.g. evl-lib)
              - grep --version
              - git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"
              - sh run.sh chaincode test golang/mychaincode
        - step:
            name: Run chaincode build
            script:
              # do this to make go module work with private repo (e.g. evl-lib)
              - git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"
              - sh run.sh chaincode build golang/mychaincode
