image: everledgerio/golang:1.12.6-alpine3.10

pipelines:
  default: # run pipeline for all branches
  - parallel:
     - step:
         name: Run chaincode unit tests
         script:
           # do this to make go module work with private repo (e.g. evl-lib)
           - git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"
           - ./run.sh chaincode test mychaincode
     - step:
         name: Run chaincode build
         script:
           # do this to make go module work with private repo (e.g. evl-lib)
           - git config --global url."git@bitbucket.org:".insteadOf "https://bitbucket.org/"
           - ./run.sh chaincode build mychaincode