image: everledgerio/golang:1.15.5-alpine3.12

pipelines:
  default:
    - parallel:
        - step:
            name: Run chaincode unit tests
            script:
              - ./fabkit chaincode test mygocc
        - step:
            name: Run chaincode build
            script:
              - ./fabkit chaincode build mygocc
