image: everledgerio/golang:1.11.5-alpine3.9-git

pipelines:
  default: # run pipeline for all branches
    - step:
        name: Run chaincode unit tests
        script:
            - export CGO_ENABLED=0
            - sh -c "./run.sh test_chaincode mychaincode"
