image: everledgerio/golang:1.11.5-alpine3.9

pipelines:
  default: # run pipeline for all branches
  - parallel:
     - step:
         name: Run chaincode unit tests
         script:
           - ./run.sh chaincode test mychaincode
     - step:
         name: Run chaincode build
         script:
             - ./run.sh chaincode build mychaincode