version: '2'

networks:
  default:
    external:
      # This value should be the same for fabric network and client
      name: ${DOCKER_NETWORK}

services:
  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: network/base/base.yaml
      service: orderer-base
    volumes:
        - ./network/channels/orderer-system-channel/genesis_block.pb:/var/hyperledger/orderer/orderer.genesis.block
        - ./network/cryptos/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ./network/cryptos/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - ./data/orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  ca.org1.example.com:
    container_name: ca.org1.example.com
    extends:
      file: network/base/base.yaml
      service: ca-base
    environment: 
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
    volumes:
      - ./network/cryptos/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    ports:
      - 7054:7054

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: network/base/base.yaml
      service: peer-base
    environment:
      # Change this value aligning with the defined docker network name
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${DOCKER_NETWORK}
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0.org1.example.com-couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - GODEBUG=netdns=go
    volumes:
        # trick: for security reasons some services such as Bitbucket Pipeline will not allow to mount volumes 
        # which are sitting outside the cloned/project directory
      - ./docker.sock/:/host/var/run/
      - ./network/cryptos/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ./network/cryptos/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
      - ./data/peer0.org1.example.com:/var/hyperledger/production
    ports:
      - 7051:7051
    depends_on:
      - peer0.org1.example.com-couchdb

  peer0.org1.example.com-couchdb:
    container_name: peer0.org1.example.com-couchdb
    extends: 
      file: network/base/base.yaml
      service: couchdb-base
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    volumes:
      - ./data/peer0.org1.example.com-couchdb:/opt/couchdb/data
    ports:
      - 5984:5984
      
  fabric-cli:
    container_name: ${CHAINCODE_UTIL_CONTAINER}
    extends:
      file: network/base/base.yaml
      service: tools-base
    tty: true
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=fabric-cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=${CONTAINER_PEER_BASEPATH}/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=${CONTAINER_PEER_BASEPATH}/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=${CONTAINER_PEER_BASEPATH}/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=${CONTAINER_PEER_BASEPATH}/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    volumes:
        # trick: for security reasons some services such as Bitbucket Pipeline will not allow to mount volumes 
        # which are sitting outside the cloned/project directory
      - ./docker.sock/:/host/var/run/
      - ./chaincode:/opt/gopath/src/${CHAINCODE_REMOTE_PATH}
      - ./network/cryptos:${CONTAINER_PEER_BASEPATH}/crypto
      - ./network/channels:${CONTAINER_PEER_BASEPATH}/channels
    depends_on:
      - ca.org1.example.com
      - orderer.example.com
      - peer0.org1.example.com

