version: '2'

services:
  ca.example.com:
    container_name: ca.example.com
    extends:
      file: ./network/docker-compose.yml
      service: ca.example.com

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: ./network/docker-compose.yml
      service: orderer.example.com

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: ./network/docker-compose.yml
      service: peer0.org1.example.com
    depends_on:
      - orderer.example.com
      - couchdb
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_default

  couchdb:
    extends:
      file: ./network/docker-compose.yml
      service: couchdb

  channel-chaincode-util:
    container_name: channel-chaincode-util
    tty: true
    extends:
      file: ./network/docker-compose.yml
      service: cli
    depends_on:
      - ca.example.com
      - peer0.org1.example.com
      - orderer.example.com
      - couchdb
    command: /bin/bash

networks:
  default:
    external:
      name: network_default