# SPDX-License-Identifier: Apache-2.0
version: '2.1'

networks:
  default:
    external:
      # This value should be the same for fabric network and client
      name: ${FABKIT_DOCKER_NETWORK}

services:
  explorerdb.mynetwork.com:
    image: hyperledger/explorer-db:${FABKIT_EXPLORER_VERSION}
    container_name: explorerdb.mynetwork.com
    hostname: explorerdb.mynetwork.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: 'pg_isready -h localhost -p 5432 -q -U postgres'
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ../data/explorerdb:/var/lib/postgresql/data

  explorer.mynetwork.com:
    image: hyperledger/explorer:${FABKIT_EXPLORER_VERSION}
    container_name: explorer.mynetwork.com
    hostname: explorer.mynetwork.com
    environment:
      - DATABASE_HOST=explorerdb.mynetwork.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - EXPLORER_SYNC_BLOCKSYNCTIME_SEC=60000
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./../network/cryptos:/tmp/crypto
      - ../data/walletstore:/opt/wallet
    ports:
      - 8090:8080
    depends_on:
      explorerdb.mynetwork.com:
        condition: service_healthy

  proms:
    container_name: proms
    image: prom/prometheus:${FABKIT_PROMETHEUS_VERSION}
    volumes:
      - ./artifacts/operations/balance-transfer/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../data/prometheus:/prometheus
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana:${FABKIT_GRAFANA_VERSION}
    volumes:
      - ./artifacts/operations/balance-transfer/balance-transfer-grafana-dashboard.json:/var/lib/grafana/dashboards/mydashboard.json
      - ./artifacts/operations/grafana_conf/provisioning:/etc/grafana/provisioning
      - ../data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
