version: "2.4"

networks:
  default:
    external:
      # This value should be the same for fabric network and client
      name: ${FABKIT_DOCKER_NETWORK}

volumes:
  console-couchdb:
    name: ${FABKIT_DOCKER_NETWORK}_console-couchdb

services:
  fabric-console:
    container_name: fabric-console
    image: ghcr.io/hyperledger-labs/fabric-console:latest
    ports:
      - "3000:3000"
    volumes:
      - ${FABKIT_HOST_ROOT}/console/env:/home/athena/env
    environment:
      - CONFIGURE_FILE=./env/config.yaml
      - DB_CONNECTION_STRING=http://admin:password@console-couchdb:5984
      - DB_SYSTEM=athena_system

  configtxlator:
    container_name: configtxlator
    image: hyperledger/fabric-tools:${FABKIT_FABRIC_VERSION}
    command: /bin/bash -c "/usr/local/bin/configtxlator start --CORS=*"
    ports:
      - "7059:7059"

  console-couchdb:
    container_name: console-couchdb
    extends:
      file: ${FABKIT_NETWORK_PATH}/base/base.yaml
      service: couchdb-base
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - "console-couchdb:/opt/couchdb/data"
    ports:
      - "5985:5984"

  proxy.peer0.org1.example.com:
    container_name: proxy.peer0.org1.example.com
    image: ghcr.io/hyperledger-labs/grpc-web:latest
    environment:
      - BACKEND_ADDRESS=peer0.org1.example.com:7051
      - SERVER_TLS_CERT_FILE=/certs/tls/server.crt
      - SERVER_TLS_KEY_FILE=/certs/tls/server.key
      - BACKEND_TLS_CA_FILES=/certs/tls/ca.crt
      - SERVER_BIND_ADDRESS=0.0.0.0
      - SERVER_HTTP_DEBUG_PORT=8080
      - SERVER_HTTP_TLS_PORT=7443
      - BACKEND_TLS=true
      - SERVER_HTTP_MAX_WRITE_TIMEOUT=5m
      - SERVER_HTTP_MAX_READ_TIMEOUT=5m
      - USE_WEBSOCKETS=true
    volumes:
      - ${FABKIT_HOST_ROOT}/network/cryptos/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/certs/tls
    ports:
      - "7443:7443"

  proxy.orderer.example.com:
    container_name: proxy.orderer.example.com
    image: ghcr.io/hyperledger-labs/grpc-web:latest
    environment:
      - BACKEND_ADDRESS=orderer.example.com:7050
      - SERVER_TLS_CERT_FILE=/certs/tls/server.crt
      - SERVER_TLS_KEY_FILE=/certs/tls/server.key
      - BACKEND_TLS_CA_FILES=/certs/tls/ca.crt
      - SERVER_BIND_ADDRESS=0.0.0.0
      - SERVER_HTTP_DEBUG_PORT=8082
      - SERVER_HTTP_TLS_PORT=7445
      - BACKEND_TLS=true
      - SERVER_HTTP_MAX_WRITE_TIMEOUT=5m
      - SERVER_HTTP_MAX_READ_TIMEOUT=5m
      - USE_WEBSOCKETS=true
    volumes:
      - ${FABKIT_HOST_ROOT}/network/cryptos/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/certs/tls
    ports:
      - "7445:7445"
