name: Create artifacts for new release

on:
  release:
    types: [published]

jobs:
  update_version_and_push_to_registry:
    name: Update Fabkit version
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use latest tag and replace in env file
        run: |
          REPO_LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "REPO_LATEST_TAG=${REPO_LATEST_TAG}"
          sed -i "s+^FABKIT_VERSION=.*+FABKIT_VERSION=${REPO_LATEST_TAG//[aA-zZ]/}+" .env
          head -n 1 .env

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          add: ".env"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            everledgerio/fabkit
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
